version: "1.0"

services:
    # install sdk and run emulator + install and run appium
    emulator:
        build:
            context: .
            dockerfile: dockerfile_emulator
            args:
                - AVD_NAME=$AVD_NAME
        image: ubuntu-android-sdk-image
        container_name: emulator-container
        volumes:
            - "$HOME/.Xauthority:/root/.Xauthority:ro"
        devices:
            - "/dev/kvm:/dev/kvm"
        network_mode: "host"
        # ports:
        #     - 5037:5037
        # privileged: true
        environment:
            - "DISPLAY=$DISPLAY"
        # command: emulator -avd ${AVD_NAME} -no-boot-anim -gpu swiftshader_indirect -no-audio
        # command: sh -c "./start.sh"
        command: ["bash", "-c", "./script.sh"]

    # appium:
    #     build:
    #         context: .
    #         dockerfile: dockerfile_appium
    #     image: appium-image
    #     container_name: appium-container
    #     network_mode: "host"
    #     ports:
    #         - 5037:5037
    #     depends_on:
    #         - emulator
    #     # command: sleep 5 && appium -p 4723 --log-level error  --session-override
    #     command: python3 main.py

    # script:
    #     image: ubuntu-android-sdk-image
    #     container_name: appium-script-container
    #     depends_on:
    #         - appium
    #     links:
    #         - appium
    #     command: python3 main.py
