FROM ubuntu:20.04



# Install and Run Appium

ENV APPIUM_VERSION=2.0.1

RUN set -uex; \
    apt-get update; \
    apt-get install -y ca-certificates curl gnupg; \
    mkdir -p /etc/apt/keyrings; \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
     | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg; \
    NODE_MAJOR=16; \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" \
     > /etc/apt/sources.list.d/nodesource.list; \
    apt-get update; \
    apt-get install nodejs -y && \
    npm install -g appium@${APPIUM_VERSION} --unsafe-perm=true --allow-root && \
    appium driver install uiautomator2 && \
    npm install -g appium-doctor --unsafe-perm=true --allow-root && \
    exit 0 && \
    npm cache clean && \
    apt-get remove --purge -y npm && \
    apt-get autoremove --purge -y && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    apt-get clean

ENV TZ="Europe/Baku"
RUN echo "${TZ}" > /etc/timezone

RUN apt-get install -y python3 python3-pip && pip install rich selenium pyperclip appium-python-client Pillow

WORKDIR /app
COPY ./app/ .

# RUN sh -c 'appium -p 4723 &'
# RUN bash -c 'sleep 5 && appium  --log-level error  --session-override   &'
# RUN bash -c 'appium -p 4723 -a localhost -pa &'

# EXPOSE 4723
